#!/usr/bin/env bash

monitor=$1
brightness=$2
current=$3

eww update brightness-current=$(echo $current | jq -Mc ".[$monitor] = $brightness")
# ddcutil --sleep-multiplier .1 --display $monitor setvcp 10 $brightness
scripts/.venv/bin/monitorcontrol --monitor $(( $monitor + 1 )) --set-luminance $brightness

