#!/usr/bin/env bash

monitor=$1
brightness=$2
current=$3

scripts/.venv/bin/monitorcontrol --monitor $(( $monitor + 1 )) --set-luminance $brightness
eww update brightness-current=$(echo $current | jq -Mc ".[$monitor] = $brightness")
